spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/blogapp
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:bloguser}
    password: ${DB_PASSWORD:blogpass}
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    com.blog.app: INFO
    root: INFO

